---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: "{{ molecule_no_log }}"
  vars:
    molecule_labels:
      owner: molecule
  tasks:
    # TODO : deal with ImagePullSecret P2

    # TODO: deal with CDI image push P1

    # FIXME : force set_fact ssh key if none provided P0
    - name: Create ssh key pair
      openssh_keypair:
        path: "{{ molecule_ephemeral_directory }}/identity_{{ item.name }}"
        size: 1024
        type: rsa
      with_items: "{{ molecule_yml.platforms  }}"

    # TODO: Allow supercharge startup while keeping default credential P2
    - name: Create cloud init with ssh identity for molecule user
      k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: "{{ item.name }}-cloud-init"
            namespace: "{{ item.namespace | default('default') }}"
          type: Opaque
          stringData:
            userdata: |-
              #cloud-config
              users:
                - name: molecule
                  sudo: ALL=(ALL) NOPASSWD:ALL
                  plain_text_passwd: molecule
                  lock_passwd: false
                  ssh_authorized_keys:
                    - {{ lookup('file', molecule_ephemeral_directory + '/identity_'+ item.name + '.pub' ) }}
      with_items: "{{ molecule_yml.platforms  }}"


    # - name: Create a PVC as a clone for same url
    #   community.general.kubevirt_pvc:
    #     name: "{{ item.name }}-disk"
    #     namespace: "{{ item.namespace | default('default') }}"
    #     size: "{{ item.disk_size | default('10Gi') }}"
    #     access_modes:
    #       - ReadWriteOnce
    #     cdi_source:
    #       pvc:
    #         namespace: "{{ item.cache_once_namespace | default('default') }}"
    #         name: "{{ item.cache_once_url | default('https://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud-2009.qcow2') | basename | replace('.','-') | replace('_','-') | lower }}"

    # # TODO : allow local build and upload
    # - name: Import disk image into CDI
    #   k8s:
    #     state: present
    #     definition:
    #       # This example assumes you are using a default storage class
    #       apiVersion: cdi.kubevirt.io/v1beta1
    #       kind: DataVolume
    #       metadata:
    #         name: "{{ item.name }}"
    #         namespace: "{{ item.namespace | default('default') }}"
    #       spec:
    #         source:
    #             http:
    #               url: "https://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud-2009.qcow2"
    #         pvc:
    #           accessModes:
    #             - ReadWriteOnce
    #           resources:
    #             requests:
    #               storage:  "{{ item.cdi_storage | default('10Gi') }}"
    #   with_items: "{{ molecule_yml.platforms  }}"

    - name: Create VM block
      block:
        - name: Create virtual machine 'myvm' and start it
          community.general.kubevirt_vm:
            state: running
            wait: true
            wait_timeout: "{{ item.wait_timeout | default(900) }}"
            name: "{{ item.name }}"
            namespace: "{{ item.namespace | default('default') }}"
            memory: "{{ item.memory | default('5Gi') }}"
            cpu_cores: "{{ item.cpu_cores | default(omit) }}"
            machine_type: "{{ item.machine_type | default('q35') }}"

            interfaces:
              - name: default
                masquerade: {}
                ports:
                  - port: 22
                network:
                  pod: {}

            # datavolumes:
            #   - name: "{{ item.name }}-data-volume"
            #     source:
            #       # pvc:
            #       #   name: "{{ item.cache_once_url | default('https://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud-2009.qcow2') | basename | replace('.','-') | replace('_','-') | lower }}"
            #       #   namespace: "{{ item.cache_once_namespace | default('default') }}"
            #       http:
            #         url: "{{ item.cache_once_url | default('https://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud-2009.qcow2') }}"
            #     pvc:
            #       accessModes:
            #         - ReadWriteOnce
            #       storage: 10Gi
            cloud_init_nocloud:
              secretRef:
                name: "{{ item.name }}-cloud-init"

            cpu_model: "{{ item.cpu_model | default(omit) }}"
            headless: "{{ item.headless | default(omit) }}"
            hugepage_size: "{{ item.hugepage_size | default(omit) }}"

            cpu_limit: "{{ item.cpu_limit | default(omit) }}"
            cpu_shares: "{{ item.cpu_shares | default(omit) }}"
            ephemeral: "{{ item.ephemeral | default(omit) }}"
            # TODO : deal with alternative disks configuration (not CDI)
            disks:
              - name: "{{ item.name }}-container-disk"
                volume:
                  containerDisk:
                    image: "{{ item.image | default('quay.io/jseguillon/kubevirt-images:focal-server-cloudimg-amd64') }}"
                    # path: "{{ item.path | default(omit) }}"
                    imagePullPolicy: "IfNotPresent"
                disk:
                  bus: virtio
          with_items: "{{ molecule_yml.platforms  }}"
          register: server

        - name: Create ssh service
          k8s:
            state: present
            definition:
              apiVersion: v1
              kind: Service
              metadata:
                name: "{{ item.name }}"
                namespace: "{{ item.namespace | default('default') }}"
              spec:
                ports:
                  - port: 22
                    protocol: TCP
                    targetPort: 22
                selector:
                  vm.cnv.io/name: "{{ item.name }}"
                type: ClusterIP
          register: service
          with_items: "{{ molecule_yml.platforms  }}"

        - name: debug servers
          debug:
            msg: "{{ item }}"
          with_items: "{{ server.results }}"

        - name: Flatten services result for use when setting instance_config
          set_fact:
            flatten_services: "{{ service.results | json_query('[].{Name: result.metadata.name, IP: result.spec.clusterIP}') }}"

        - name: Populate instance config dict
          set_fact:
            instance_conf_dict: |
              { 'instance': "{{ item.kubevirt_vm.metadata.name }}",
                'address': "{{ flatten_services | json_query(query) }}",
                'user': "molecule",
                'port': "22",
                'identity_file':  "{{ molecule_ephemeral_directory }}/identity_{{ item.kubevirt_vm.metadata.name }}"
              }
          vars:
            query: "[?Name=='{{ item.kubevirt_vm.metadata.name }}'].IP | [0]"
          with_items: "{{ server.results }}"
          register: instance_config_dict

        - name: debug instances
          debug:
            msg: "{{ instance_conf_dict }}"

        - name: debug ssh port test
          debug:
            msg: "{{ flatten_services | json_query(query) }}"
          vars:
            query: "[?Name=='{{ item.kubevirt_vm.metadata.name }}'].IP | [0]"
          with_items: "{{ server.results }}"

        - name: Wait 300 seconds for port 22 to become open
          wait_for:
            timeout: 480
            port: 22
            host: "{{ flatten_services | json_query(query) }}"
            delay: 10
          vars:
            query: "[?Name=='{{ item.kubevirt_vm.metadata.name }}'].IP | [0]"
          with_items: "{{ server.results }}"

      rescue: 
        - name: get all resources
          k8s_info: 
            kind: "{{ item }}"
          with_items: 
            - Pod
            - Service
        - name: get all resources
          k8s_info: 
            kind: "{{ item }}"
            api: kubevirt.io/v1alpha3
          with_items: 
            - VirtualMachine
            - VirtualMachineInstance

        - name: fail 
          fail: 
            msg: Got in rescue to get more logs but cannot continue (Maybe better do handler)
            
    - name: Convert instance config dict to a list
      set_fact:
        instance_conf: "{{ instance_config_dict.results | map(attribute='ansible_facts.instance_conf_dict') | list }}"

    - name: Dump instance config
      copy:
        content: "{{ instance_conf | to_json | from_json | to_yaml }}"
        dest: "{{ molecule_instance_config }}"
        mode: 0600
